name: SharePos
version: 1.0.0
main: ru.sharepos.SharePosPlugin
api-version: 1.21
author: YourName
description: Plugin for sharing coordinates with other players

commands:
  sharepos:
    description: Share your current position with other players
    usage: /sharepos [player] or /sharepos all
    aliases: [sp, pos]

permissions:
  sharepos.use:
    description: Allows player to share coordinates
    default: true
  sharepos.all:
    description: Allows player to share coordinates with all players
    default: op